version: '3.9'
services:
  # redis:
  #   restart: always
  #   image: redis:5
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - db-net

  backend:
    container_name: spa_backend
    command : "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: spadb

    restart: on-failure
    depends_on:
      - db
        # condition: service_healthy

  db:
    image: mysql:8.0.31
    volumes:
      - todo-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spadb

volumes:
  todo-mysql-data:

  # frontend:
  #   restart: always
  #   command : npm start
  #   container_name: front
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   depends_on:
  #     - api
  #   networks:
  #     - db-net

networks:
  db-net:
    driver: bridge