# Generated by Django 4.1.2 on 2023-07-07 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_detail',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('NOT ACTIVE', 'Not Active'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
